Upgrade operator sdk + a few fixes (#8)
* Use of lpass status to validate login and disabling logout command

* Namespace are handed by helm and should not be hardcoded

* Use a correct log message in logout function.

* Remove uneeded id from secretName

* upgrade to operator-sdk 0.8.2 and golang 1.17

* upgrade to operator-sdk 0.17.2

* fix missing required namespace in ClusterRoleBinding

* remove docker login before push in makefile

echo  | docker login -u paullaffitte
Error: Cannot perform an interactive login from a non TTY device

* upgrade to operator-sdk 0.18.2

* upgrade to operator-sdk 0.19.4

* upgrade to operator-sdk 1.0.1 and crdVersion v1

* upgrade to operator-sdk 1.5.2

* remove Apache 2.0 references since the project is under MIT

* fix syncPolicy is optional

* remove duplicate setups of lastpass controller in main.go

* add flag (and helm value) to define a template for secrets names

* restore repository default value to edgelevel instead of enix

* restore logout function but stop calling it

Co-authored-by: David Donchez <david.donchez@enix.fr>
Co-authored-by: Alexandre Buisine <alexandrejabuisine@gmail.com>